# Generated by Django 4.2.4 on 2023-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
