# Generated by Django 4.2.4 on 2023-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_societymember_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='address',
        ),
        migrations.AlterField(
            model_name='societymember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
